//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopProduct
    {
        public System.Guid Id { get; set; }
        public int TotalSale { get; set; }
        public System.Guid ProductId { get; set; }
        public System.Guid ProductCategoryId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
